# Pages CMS: content is stored in _data/*.yml and markdown files. Keep paths in sync when editing.

settings:
  content:
    merge: true

media:
  - name: images
    label: Images
    input: assets/img
    output: /assets/img
    path: assets/img

content:
  - name: contact
    label: Contact
    type: file
    path: _data/contact.yml
    format: yaml
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: company, label: Company, type: string }
      - { name: address, label: Address, type: text }
      - { name: maps, label: Maps URL, type: string }
      - { name: tel, label: Phone, type: string }
      - { name: call, label: Call button, type: string }
      - name: email
        label: Email
        type: object
        fields:
          - { name: address, label: Email address, type: string }
          - { name: subject, label: Subject, type: string }

  - name: seo
    label: SEO
    type: file
    path: _data/seo.yml
    format: yaml
    fields:
      - { name: url, label: Site URL, type: string }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: image, label: Social sharing image (optional), type: image }
      - { name: favicon, label: Favicon, type: image }

  - name: nav
    label: Navigation
    type: file
    path: _data/nav.yml
    format: yaml
    fields:
      - name: links
        label: Nav links
        type: object
        list: 
          collapsible:
            collapsed: true
            summary: "{fields.label}"
        fields:
          - { name: label, label: Label, type: string }
          - { name: href, label: Link, type: string }

  - name: footer
    label: Footer
    type: file
    path: _data/footer.yml
    format: yaml
    fields:
      - { name: company_name, label: Company name, type: string }
      - name: links
        label: Links
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.label}"
        fields:
          - { name: ref, label: Page ref (terms, privacy), type: string }
          - { name: label, label: Label, type: string }

  - name: terms
    label: Terms
    type: file
    path: terms.md
    format: yaml-frontmatter
    fields:
      - { name: layout, label: Layout, type: string, default: article }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: privacy
    label: Privacy
    type: file
    path: privacy.md
    format: yaml-frontmatter
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, label: Layout, type: string, default: article }
      - { name: body, label: Body, type: rich-text, description: "Don't remove {{ ... }} Liquid placeholders for contact info." }

  - name: posts
    label: Posts
    type: collection
    path: _posts
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: desc
    fields:
      - { name: layout, label: Layout, type: string, default: default }
      - { name: title, label: Title, type: string }
      - { name: permalink, label: Permalink (optional, e.g. /blog/my-post/), type: string }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }

  - name: works
    label: Works
    type: collection
    path: _works
    format: yaml-frontmatter
    filename: "{name}.md"
    view:
      fields: [ title, name ]
      primary: title
      sort: [ title ]
    fields:
      - { name: name, label: URL slug, type: string, description: "Slug for URL and filename (e.g. sample-project)." }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: hero_image, label: Hero image, type: image }
      - { name: layout, label: Layout, type: string, default: default }
      - { name: body, label: Body, type: rich-text }